### ISSUE TITLE
Transition replicated compiler passes

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/moose#315]
- [x] symbolic graph generation (https://github.com/tf-encrypted/runtime/pull/306)
- [x] attempt to reduce code duplications and copy/paste (https://github.com/tf-encrypted/runtime/pull/306)
- [x] high-level `MulOp` and dealing with implicit state (in this case setup needed for mid-level `RepMulOp`) (https://github.com/tf-encrypted/runtime/pull/317)
- [ ] `SymbolicExecutor` with similar interface as the other executors
- [x] `with`-like syntactic sugar (https://github.com/tf-encrypted/runtime/pull/313/)
- [ ] partial symbolic executor (eg only lower replicated placements) by eg parameterizing `SymbolicContext` with a strategy that decides which ops are considered for concrete execution (https://github.com/tf-encrypted/runtime/pull/343)
- [x] adapt code to having `plc` on operations instead of operators (https://github.com/tf-encrypted/runtime/pull/322)
- [x] adapt code to support closure kernels (https://github.com/tf-encrypted/runtime/pull/328)
- [ ] merge operations structs
- [x] add ability to extract placement from (input) value (see `RepShareOp`) (https://github.com/tf-encrypted/runtime/pull/321)
- [ ] add ability to insert `ReplicatedSetupOps` and use these when lowering
- [ ] make `ctx` less omnipresent 
- [ ] determine if `SymbolicValue`could/should contain a reference to the (symbolic) context, to allow `Add`, `Mul` etc directly on symbolic values without macros
- [ ] well-formed pass (https://github.com/tf-encrypted/runtime/issues/447)
- [x] introduce proper error handling where needed, eg get rid of potentially failing `unwrap`s -> https://github.com/tf-encrypted/runtime/issues/339
- [x] variadic support (currently most code is only nullary-ternary) -> https://github.com/tf-encrypted/runtime/issues/336
- [x] async kernels -> https://github.com/tf-encrypted/runtime/issues/337
- [x] session argument -> https://github.com/tf-encrypted/runtime/issues/340
- [x] typed operator kernels -> https://github.com/tf-encrypted/runtime/issues/341
