### ISSUE TITLE
Replicated Square Root Implementation

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/moose#563]
This is a larger development issue, blocked by several smaller issues.
- [ ] Implement MSBIndex for `RepFixed(x)` #602 
- [ ] Implement SimplifiedNormSq for `RepFixed(x)` https://github.com/tf-encrypted/runtime/issues/564
- [ ] Implement one of: https://github.com/tf-encrypted/runtime/issues/565
   - Replicated fixedpoint reciprocal: given `Rep(w)` for fixedpoint `w`, compute `1 / Rep(w)`.
   - Public-private division of fixedpoint: `a / Rep(w)` for `Rep(w)` for fixedpoint `w` and `a` ([Scale example](https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/master/WebAssembly/scale_std/src/fixed_point.rs#L935))
- [ ] Optional: implement a generic Goldschmidt iteration functionality https://github.com/tf-encrypted/runtime/issues/566
- [ ] Implement Sqrt for `RepFixed(x)`
