### ISSUE TITLE
Support models from scikit-learn / xgboost via ONNX

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/moose#750]
Models we care to support ASAP
- [x] Linear regression #742 
- [x] Logistic Regression #749
- [x] XGBoost Regression #752 
- [x] XGBoost Binary Classification #753 

Also includes some quality check/cleanup issues
- [ ] Benchmarking predictions we care about most in runtime benchmarks #746
- [x] Testing coverage of our linear regression implementation for various sklearn models #747
- [x] Testing coverage of our linear classifier implementation for various sklearn models
- [x] Ops needed for correct multiclass classification output in TreeEnsembleClassifier #771 
- [x] Testing coverage of our tree ensemble implementation against tree  ensemble models from [`sklearn.ensemble`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.ensemble) #762
